### ISSUE TITLE
Publish to npm

### ISSUE THREAD

**Issue by wyattdanger** [accesslint/accesslint.js#18]
Can we  publish accesslint.js to npm? It would be preferable to be able to manage it via `npm install` than via copying/pasting a built file into a `vendor` directory.

**Comment by ckundo** [comment]
What's the convention for naming for a standalone library in npm? Does calling it strictly `accesslint` create confusion with the accesslint cli command?

**Comment by wyattdanger** [comment]
Yes that's a good point. You can `npm install accesslint-js`

**Comment by bfred-it** [comment]
No no, `accesslint` is fine, "js" is redundant. The cli is already there as [`accesslint-cli`](https://www.npmjs.com/package/accesslint-cli)

**Comment by ckundo** [comment]
@wyattdanger what about including via a CDN url? I'm working on that now as part of #23. Depending on your build process, you may be able to automate inclusion of the CDN resource into the project. Otherwise, you can use a `script` tag and conditionally include the resource.

**Comment by ckundo** [comment]
Just stood up a CDN endpoint to load the current version of the built resource: https://cdn.accesslint.com/accesslint-1.1.2.js cc @wyattdanger

**Comment by CExAdamJ** [comment]
Sorry to raise this from the dead, but if this project is still maintained I would also be interested in managing this as dependency with NPM instead of relying on a CDN.
