### ISSUE TITLE
Host in a CDN?

### ISSUE THREAD

**Issue by TheTedAdams** [accesslint/accesslint.js#23]
I think this script is an excellent candidate to keep around as a bookmarklet.

Just to try it out I used this:

`javascript:(function(){document.body.appendChild(document.createElement('script')).src='https://github.com/accesslint/accesslint.js/releases/download/v1.1.2/accesslint.js';})();`

Works great, I get output in console, but would be nice if there was a latest hosted either in a CDN or just on github where I could reference it.

**Comment by ckundo** [comment]
@thetedadams yes! I'll finish configuring this soon. :+1:

**Comment by ckundo** [comment]
@TheTedAdams you can now load the compiled resource from https://cdn.accesslint.com/accesslint-1.1.2.js (hosted on CloudFront).
