### ISSUE TITLE
Accesslint keeps trying to change my <h1> to <h3>

### ISSUE THREAD

**Issue by End3rYT** [AccessLint/accesslint.js#31]
I was working on my organization's webpage and made a commit to one of my student's patch when I saw this:

> Accesslint has left review comments

The strangest part was that it wanted me to edit my HTML:

> `- <h1>`
> `+ <h3>`

I knew that headings went from most important (h1) to least important (h6)

Does anybody know why this is happening?

**Comment by ckundo** [comment]
@End3rYT none of the AccessLint libraries make change suggestions, so the issue you described unrelated to our projects. NB: if you're looking for review comments, use https://github.com/marketplace/accesslint.
